---
- name: testing on loops
  hosts: "{{node_name}}"
  become: true 
  tasks:
  - name: Installing nginx
    package: 
         name: "{{ item }}"
         state: latest
    
    with_items:
       - nginx-common
       - nginx-core
       - nginx

  - name: nginx
    service: name=nginx state=started
    
