---
- name: User Creations
  hosts: "{{node_name}}"
  become: true 
  tasks:

  - name: more complex items to add several users
    user:
       name: "{{ item.name }}"
       groups: "{{ item.groups }}"
       state: absent
    with_items:
       - { name: 'alice', groups: "ansible, vagrant" }
       - { name: 'kaala', groups: ansible }
    when: ansible_distribution == 'Debian' and ansible_distribution == 'Ubuntu'
