---
- hosts: all
  gather_facts: no
  tasks:
  - name: checking the status of the nodes from 1-3
    ping:

- hosts: node3
  become: true
  tasks:
  - name: Running the Fdisk commands on node3
    command: fdisk -l
    register: fdisk_output

  - debug: 
       msg: "{{ fdisk_output.stdout }}" 
